version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building the Docker images..."
      - docker compose build

  post_build:
    commands:
      - echo "Running tests..."
      - docker compose run app python -m unittest discover -v -s ./src/tests/domain -p "test_*.py"
