version: 0.2

phases:
  install:
    runtime-versions:
      docker: 23
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building the Docker images..."
      - docker compose build

  post_build:
    commands:
      - echo "Running tests..."
      - docker compose run app python -m unittest discover -v -s ./src/tests/domain -p "test_*.py"
      - |
        if [ "$CODEBUILD_WEBHOOK_EVENT" = "PULL_REQUEST_MERGED" ]; then
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
          if [ "$CODEBUILD_WEBHOOK_BASE_REF" = "refs/heads/develop" ]; then
            echo "Pushing the Docker image to the develop repository..."
            docker tag camp-gear-sale-app:latest $ECR_REPOSITORY_URL:dev-latest
            docker push $ECR_REPOSITORY_URL:dev-latest
          elif [ "$CODEBUILD_WEBHOOK_BASE_REF" = "refs/heads/main" ]; then
            echo "Pushing the Docker image to the production repository..."
            docker tag camp-gear-sale-app:latest $ECR_REPOSITORY_URL:prd-latest
            docker push $ECR_REPOSITORY_URL:prd-latest
          else
            echo "Skipping Docker image push for non-develop and non-main branches"
          fi
        else
          echo "Skipping Docker image push for non-merge event"
        fi
